package constant;

public class Constant {
    public final static int TIME_WAIT = 20;
    public static final String TEXT_BOX_USERNAME = "Nhập số điện thoại của bạn";
    public static final String TEXT_BOX_PASSWORD = "Nhập mật khẩu";
    public static final String MESSAGE_SUCCESS_LOGIN = "Đăng nhập thành công";
    public static final String MESSAGE_FAIL_LOGIN = "Tên đăng nhập hoặc mật khẩu sai ";
    public static final String MESSAGE_SUCCESS_LOGOUT = "Đăng xuất thành công";
    public static final String TITLE_LOGIN_SMART_TV = "ĐĂNG NHẬP SMART TV, WEBSITE";
    public static final String TITLE_DEVICE_MANAGE = "QUẢN LÝ THIẾT BỊ";
    public static final String TITLE_INFORM_SETTING = "CÀI ĐẶT THÔNG BÁO";
    public static final String MESSAGE_INVALID_OTP = "Mã otp sai hoặc đã hết hạn";
    public static final String MESSAGE_EXPIRED_OTP = "Mã OTP của bạn đã hết hạn";
    public static final String MESSAGE_LOGOUT_SUCCESS_DEVICE = "Đăng xuất thiết bị thành công";
    public static final String MESSAGE_UPDATE_SUCCESS_INFORM = "Cập nhật thành công";
    public static final String MESSAGE_UPDATE_FAIL_EMAIL_INFORM = "Vui lòng đúng định dạng email";
    public static final String MESSAGE_UPDATE_FAIL_NAME = "Vui lòng nhập tên";
    public static final String MESSAGE_LOGIN_NOTICE = "Bạn cần đăng nhập để sử dụng tính năng này.";
    public static final String TITLE_DISCOUNT_CODE = "MÃ KHUYẾN MẠI";
    public static final String TITLE_HISTORY_BY_SUB = "LỊCH SỬ MUA GÓI";
    public static final String NAME_HISTORY_BY_ALL = "Tất cả";
    public static final String NAME_HISTORY_SUB = "Đăng ký";
    public static final String NAME_HISTORY_RENEW = "Gia hạn";
    public static final String NAME_HISTORY_CANCEL = "Hủy gói";
    public static final String TITLE_LIST_SUB = "DANH SÁCH GÓI CƯỚC";
    public static final String TITLE_MAIN_POLICY_TERM = "ĐIỀU KHOẢN & CHÍNH SÁCH";
    public static final String TITLE_POLICY_TERM = "CHÍNH SÁCH BẢO MẬT & ĐIỀU KHOẢN SỬ DỤNG";
    public static final String TITLE_POLICY_TERM_1 = "1. KHAI BÁO KHI SỬ DỤNG";
    public static final String TITLE_INPUT_CODE = "Nhập mã khuyến mại";
    public static final String TEXT_BOX_INPUT_CODE = "Mã gồm 6 ký tự";
    public static final String MESSAGE_ERROR_PASS = "Mật khẩu phải từ 6 ký tự trở lên";
    public static final String MESSAGE_SET_PASSWORD = "Vui lòng tạo mật khẩu từ 6 ký tự trở lên";
    public static final String MESSAGE_HELLO_SET_PASSWORD = "Xin chào";
    public static final String TEXT_INPUT_PASSWORD = "Nhập mật khẩu của bạn";
    public static final String TEXT_INPUT_CONFIRM_PASSWORD = "Nhập lại mật khẩu";
    public static final String MESS_SIGN_UP_COMPARE_PASS = "Mật khẩu xác nhận chưa trùng khớp";
    public static final String TITLE_INPUT_OTP = "Nhập mã OTP được gửi tới số ";
    public static final String MESS_ERROR_FORGOT_PASS = "Password không được để trống";
    public static final String MESS_NOTICE_MORE_3_DEVICES = "Tài khoản của bạn đã đăng nhập quá 3 thiết bị. Vui lòng chọn tiếp tục để đăng xuất khỏi thiết bị đã đăng nhập cũ nhất.";
    public static final String TEXT_INPUT_SEARCH = "Nhập nội dung cần tìm kiếm";
    public static final String MESS_NO_RESULT_FOUND = "Không có kết quả tìm kiếm";
    public static final String MESS_FIND_OTHER_RESULT = "Hãy thử tìm kiếm với từ khóa khác.";
}
